# switch activator from ctrl-b to ctrl-a
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# pane border colors
set -g pane-active-border-style bg=default,fg=magenta
set -g pane-border-style fg=green
