# switch activator from ctrl-b to ctrl-a
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# tmux plugin manager (tpm)
# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# dracula theme
set -g @plugin 'dracula/tmux'
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-cpu-usage true
set -g @dracula-day-month false
set -g @dracula-show-battery false
set -g @dracula-show-network false

# auto-install tpm (for new machines)
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
# initialize tpm (must be at bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
