[global]
username = 1260251760
# password = password
use_keyring = true
backend = pulseaudio
device_name = archetype
bitrate = 320
cache_path = /home/timothy/.cache/spotifyd
no_audio_cache = false
initial_volume = 100
volume_normalisation = false
device_type = computer
