#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=/home/timothy/bin:$PATH

# import aliases
source $HOME/.aliases

# get colors to work properly in tmux
# export TERM=xterm-256color

# make applications use wayland
# export MOZ_ENABLE_WAYLAND=true
# export QT_QPA_PLATFORM=wayland
source /usr/share/nvm/init-nvm.sh
